name: release-solution-to-prod
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  

  release-to-staging:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://orgff96f58a.crm4.dynamics.com/'
        user-name: 'alans@CRM759616.OnMicrosoft.com'
        password-secret: ${{ secrets.password2 }}
        solution-file: C:\Users\gaia.d.giliberto\Desktop\MPS\RFC\solutions\ALMLab\ALMLab_1_0_0_2.zip
        force-overwrite: true
        publish-changes: true
